RAW_DATA = [
    {
        "name": "Iman Kalyan Majumder",
        "year": 2024,
        "handle": "IKMajumder",
        "gender": "male",
    },
    {
        "name": "Manish Kundu",
        "year": 2023,
        "handle": "manish.17",
        "gender": "male",
    },
    {
        "name": "Sounak Majumder",
        "year": 2023,
        "handle": "coder_sounak",
        "gender": "male",
    },
    {
        "name": "Sushobhan Mahato",
        "year": 2024,
        "handle": "Sushobhan_4",
        "gender": "male",
    },
    {
        "name": "Tanmay Mahato",
        "year": 2024,
        "handle": "tanmay121",
        "gender": "male",
    },
    {
        "name": "Prince Kumar",
        "year": 2024,
        "handle": "Unstoppable_1",
        "gender": "male",
    },
    {
        "name": "Anoushka Patra",
        "year": 2024,
        "handle": "purpleberry3.14",
        "gender": "female",
    },
    {
        "name": "Vijay Vaswani",
        "year": 2024,
        "handle": "Vaswani786",
        "gender": "male",
    },
    {
        "name": "Soham Das",
        "year": 2023,
        "handle": "the_distortion",
        "gender": "male",
    },
    {
        "name": "Devanshu Chatterjee",
        "year": 2024,
        "handle": "1_DC",
        "gender": "male",
    },
    {
        "name": "Priyanshu",
        "year": 2023,
        "handle": "Priyanshu_0514",
        "gender": "male",
    },
    {
        "name": "Himanshu Pandey",
        "year": 2022,
        "handle": "Harry_3",
        "gender": "male",
    },
    {
        "name": "Priyanshi Agarwal",
        "year": 2023,
        "handle": "priyanshi3008",
        "gender": "female",
    },
    {
        "name": "Voleti Dharma Nandana Rajkumar",
        "year": 2023,
        "handle": "rajkumarvoleti",
        "gender": "male",
    },
    {
        "name": "Md Fahad",
        "year": 2021,
        "handle": "fahadmd16",
        "gender": "male",
    },
    {
        "name": "Swarnali Mondal",
        "year": 2023,
        "handle": "swar_am",
        "gender": "female",
    },
    {
        "name": "Soham Pal",
        "year": 2023,
        "handle": "soham0_0",
        "gender": "male",
    },
    {
        "name": "Adarsh Jaiswal",
        "year": 2024,
        "handle": "crackarsh",
        "gender": "male",
    },
    {
        "name": "Iman Kalyan Majumder",
        "year": 2024,
        "handle": "IKMajumder",
        "gender": "male",
    },
    {
        "name": "Avantika Singh",
        "year": 2023,
        "handle": "Avan1608",
        "gender": "female",
    },
    {
        "name": "Tanmay Mahato",
        "year": 2024,
        "handle": "tanmay121",
        "gender": "male",
    },
    {
        "name": "Karmanya Gupta",
        "year": 2023,
        "handle": "Aestroix",
        "gender": "male",
    },
    {
        "name": "Aishwarya Deb",
        "year": 2023,
        "handle": "aishwarya2109",
        "gender": "female"
    },
    {
        "name": "SUVAM DEY",
        "year": 2024,
        "handle": "YedMavus",
        "gender": "male",
    },
    {
        "name": "Sushobhan Mahato",
        "year": 2024,
        "handle": "Sushobhan_4",
        "gender": "male",
    },
    {
        "name": "Subhadip Maji",
        "year": 2023,
        "handle": "atheistsoldier",
        "gender": "male",
    },
    {
        "name": "SIMEET NAYAN",
        "year": 2024,
        "handle": "kora_kagaz02",
        "gender": "male",
    },
    {
        "name": "Sainath Tallam",
        "year": 2023,
        "handle": "SainathTallam",
        "gender": "male",
    },
    {
        "name": "Preyas Patel",
        "year": 2023,
        "handle": "bbu_0078",
        "gender": "male",
    },
    {
        "name": "Arghyadeep Saha",
        "year": 2024,
        "handle": "fleabag",
        "gender": "male",
    },
    {
        "name": "Neeraj Pratap Hazarika",
        "year": 2024,
        "handle": "NeerajHazarika",
        "gender": "male",
    },
    {
        "name": "Subhadeep Das",
        "year": 2024,
        "handle": "subhadeepdas20011029",
        "gender": "male",
    },
    {
        "name": "Arindam Majumder",
        "year": 2023,
        "handle": "i_m_arin",
        "gender": "male",
    },
    {
        "name": "Raunak Gayen",
        "year": 2024,
        "handle": "RaunakGN",
        "gender": "male",
    },
    {
        "name": "Anirban Sikder",
        "year": 2023,
        "handle": "BReaking_COde",
        "gender": "male",
    },
    {
        "name": "Hrittik Bania",
        "year": 2024,
        "handle": "Diamond_21Aug",
        "gender": "male",
    },
    {
        "name": "Ariv Debnath",
        "year": 2024,
        "handle": "ariv_10",
        "gender": "male",
    },
    {
        "name": "Jyoti Anjaly",
        "year": 2023,
        "handle": "Sirfiri",
        "gender": "female",
    },
    {
        "name": "Niket bahety",
        "year": 2024,
        "handle": "Niket_Bahety",
        "gender": "male",
    },
    {
        "name": "Vishwateja Rapolu",
        "year": 2023,
        "handle": "vishwa_teja",
        "gender": "male",
    },
    {
        "name": "Preyas Patel",
        "year": 2023,
        "handle": "bbu_0078",
        "gender": "male",
    },
    {
        "name": "Kulin Kumar",
        "year": 2024,
        "handle": "menace_54",
        "gender": "male",
    },
    {
        "name": "Komal Shaw",
        "year": 2023,
        "handle": "komal55",
        "gender": "female",
    },
    {
        "name": "Astha Kumari",
        "year": 2023,
        "handle": "asthakri50",
        "gender": "female",
    },
    {
        "name": "Rajdeep Ghosh",
        "year": 2023,
        "handle": "Rajdeep2k",
        "gender": "male",
    },
    {
        "name": "Debopriya Roy",
        "year": 2024,
        "handle": "dpriya.jsr",
        "gender": "male",
    },
    {
        "name": "Prince Kumar",
        "year": 2024,
        "handle": "Unstoppable_1",
        "gender": "male",
    },
    {
        "name": "Dipanwita Rano",
        "year": 2024,
        "handle": "dipanwitarano",
        "gender": "female",
    },
    {
        "name": "Proggya Chakraborty",
        "year": 2024,
        "handle": "taitay",
        "gender": "female",
    },
    {
        "name": "Vinita Yadav",
        "year": 2024,
        "handle": "vinita_1701",
        "gender": "female",
    },
    {
        "name": "raunak kumar",
        "year": 2024,
        "handle": "risky_1930",
        "gender": "male",
    },
    {
        "name": "Monalisa Das",
        "year": 2024,
        "handle": "monali",
        "gender": "female",
    },
    {
        "name": "cheruku shailendra",
        "year": 2024,
        "handle": "Shailendra_cheruku",
        "gender": "male",
    },
    {
        "name": "Karmanya Gupta",
        "year": 2023,
        "handle": "Aestroix",
        "gender": "male",
    },
    {
        "name": "Prerna Gupta",
        "year": 2023,
        "handle": "ron_weasley27",
        "gender": "female",
    },
    {
        "name": "Pankhuri Goel",
        "year": 2023,
        "handle": "pankhuri_goel",
        "gender": "female",
    },
    {
        "name": "Kiranmoy Saha",
        "year": 2024,
        "handle": "saha_kiranmoy",
        "gender": "male",
    },
    {
        "name": "Anish De",
        "year": 2023,
        "handle": "anishde85",
        "gender": "male",
    },
    {
        "name": "Subhrajit Dey",
        "year": 2024,
        "handle": "Subhrajit123",
        "gender": "male",
    },
    {
        "name": "Sathi Naga Sai Maheswara Reddy",
        "year": 2024,
        "handle": "Maheswar003",
        "gender": "male",
    },
    {
        "name": "Reeju Bhattacharya",
        "year": 2024,
        "handle": "reejubhai",
        "gender": "male",
    },
    {
        "name": "Suddhabrato Ghosh",
        "year": 2024,
        "handle": "psychedelickid",
        "gender": "male",
    },
    {
        "name": "SUBHAJIT SAMANTA",
        "year": 2024,
        "handle": "Subhajit022",
        "gender": "male",
    },
    {
        "name": "Ritwik Kundu",
        "year": 2024,
        "handle": "rick3300",
        "gender": "male",
    },
    {
        "name": "Ankush Datta",
        "year": 2024,
        "handle": "sardonyx",
        "gender": "male",
    },
    {
        "name": "Suvrajit Mullick",
        "year": 2024,
        "handle": "Suvo_007",
        "gender": "male",
    },
    {
        "name": "HARISH AMAN",
        "year": 2024,
        "handle": "JLKryptonite",
        "gender": "male",
    },
    {
        "name": "Neeraj Pratap Hazarika",
        "year": 2024,
        "handle": "NeerajHazarika",
        "gender": "male",
    },
    {
        "name": "Chandresh Patel",
        "year": 2024,
        "handle": "Chand1947",
        "gender": "male",
    },
    {
        "name": "KONETI CHANDRAKANT",
        "year": 2024,
        "handle": "konetichandrakant",
        "gender": "male",
    },
    {
        "name": "Sainath Tallam",
        "year": 2023,
        "handle": "SainathTallam",
        "gender": "male",
    },
    {
        "name": "PENUGONDA S M S N RAJESH",
        "year": 2024,
        "handle": "rajeshpenugonda6",
        "gender": "male",
    },
    {
        "name": "Nishant Bhadana",
        "year": 2024,
        "handle": "nishant_bhadana",
        "gender": "male",
    },
    {
        "name": "Hrittik Bania",
        "year": 2024,
        "handle": "Diamond_21Aug",
        "gender": "male",
    },
    {
        "name": "Abhash kumar",
        "year": 2024,
        "handle": "abhash6406",
        "gender": "male",
    },
    {
        "name": "Subham Bhansali",
        "year": 2024,
        "handle": "Subham4",
        "gender": "male",
    },
    {
        "name": "Sreeja Reddy Goli",
        "year": 2024,
        "handle": "shrijareddy",
        "gender": "female",
    },
    {
        "name": "Tathagata Ghosh",
        "year": 2024,
        "handle": "tathagata_010",
        "gender": "male",
    },
    {
        "name": "Sourit Sarkar",
        "year": 2024,
        "handle": "sourit_",
        "gender": "male",
    },
    {
        "name": "Anushuya Patra",
        "year": 2024,
        "handle": "anu_1804",
        "gender": "female",
    },
    {
        "name": "Vardhan Kumar Kothapally",
        "year": 2024,
        "handle": "vardhan_19",
        "gender": "male",
    },
    {
        "name": "Souvik Dey",
        "year": 2024,
        "handle": "sd111000",
        "gender": "male",
    },
    {
        "name": "Kevin Kingslin",
        "year": 2024,
        "handle": "CrimsonNinja",
        "gender": "male",
    },
    {
        "name": "KODAVALI SRI SURYA VAMSI",
        "year": 2024,
        "handle": "k.srisuryavamsi",
        "gender": "male",
    },
    {
        "name": "Divi Srivastava",
        "year": 2024,
        "handle": "mass_2701",
        "gender": "female",
    },
    {
        "name": "RUDRESHWAR BARANWAL",
        "year": 2024,
        "handle": "RUDRA_2812",
        "gender": "male",
    },
    {
        "name": "Jaji Pravallika Gottapu",
        "year": 2024,
        "handle": "Jaji_Pravallika",
        "gender": "female",
    },
    {
        "name": "Kamal Pathak",
        "year": 2023,
        "handle": "DAT_BOI",
        "gender": "male",
    },
    {
        "name": "Vishal",
        "year": 2024,
        "handle": "Rockypil321",
        "gender": "male",
    },
    {
        "name": "Sai Teja Behera",
        "year": 2024,
        "handle": "sai_teja.",
        "gender": "male",
    },
    {
        "name": "Shreyoshi Chakraborty",
        "year": 2024,
        "handle": "shreyoshi5000",
        "gender": "female",
    },
    {
        "name": "Bikramjit Saha",
        "year": 2024,
        "handle": "biki_coder",
        "gender": "male",
    },
    {
        "name": "Adityaraj Debath",
        "year": 2024,
        "handle": "ARD1205",
        "gender": "male",
    },
    {
        "name": "Raunak kumar",
        "year": 2024,
        "handle": "Risky_1930",
        "gender": "male",
    },
    {
        "name": "VISHAL BHANJA",
        "year": 2024,
        "handle": "code_vishal18",
        "gender": "male",
    },
    {
        "name": "Subhrajit Dey",
        "year": 2024,
        "handle": "Subhrajit123",
        "gender": "male",
    },
    {
        "name": "Akhil Khader",
        "year": 2024,
        "handle": "akhbisk",
        "gender": "male",
    },
    {
        "name": "Sejal Shreya",
        "year": 2024,
        "handle": "sejal_shreya",
        "gender": "female",
    },
    {
        "name": "Sujal Modanwal",
        "year": 2023,
        "handle": "summan_gud",
        "gender": "male",
    },
    {
        "name": "Subhadeep Das",
        "year": 2024,
        "handle": "subhadeepdas20011029",
        "gender": "male",
    },
    {
        "name": "Rishita Shaw",
        "year": 2024,
        "handle": "rxshxta_",
        "gender": "female",
    },
    {
        "name": "Karra Ashish Reddy",
        "year": 2025,
        "handle": "AshishLimitless_4480",
        "gender": "male",
    },
    {
        "name": "KINGSHUK BARUA",
        "year": 2023,
        "handle": "Kingshuk_31",
        "gender": "male",
    },
    {
        "name": "Nikhil Joshi",
        "year": 2023,
        "handle": "nickjosi",
        "gender": "male",
    },
    {
        "name": "Manav Sarkar",
        "year": 2024,
        "handle": "manav_sarkar",
        "gender": "male",
    },
    {
        "name": "SANMAI REDDY YAMAGONDA",
        "year": 2025,
        "handle": "sanmai_reddy123",
        "gender": "male",
    },
    {
        "name": "Vinit Ranjan",
        "year": 2025,
        "handle": "Vinitranjansah",
        "gender": "male",
    },
    {
        "name": "Atrayee Samanta",
        "year": 2025,
        "handle": "atrayee03",
        "gender": "female",
    },
    {
        "name": "Aviral Yadav",
        "year": 2025,
        "handle": "aviral_yadav",
        "gender": "male",
    },
    {
        "name": "Sanghamitra De",
        "year": 2025,
        "handle": "thevyomonaut",
        "gender": "female",
    },
    {
        "name": "Dwaipayan Biswas",
        "year": 2025,
        "handle": "Debcode",
        "gender": "male",
    },
    {
        "name": "Arvind Kumar",
        "year": 2025,
        "handle": "arvind0266",
        "gender": "male",
    },
    {
        "name": "Sai Rugved",
        "year": 2025,
        "handle": "rugved.27",
        "gender": "male",
    },
    {
        "name": "Abhijit Saha",
        "year": 2025,
        "handle": "abhijitsaha",
        "gender": "male",
    },
    {
        "name": "Dhruv Jhunjhunwala",
        "year": 2025,
        "handle": "dhruvj25",
        "gender": "male",
    },
    {
        "name": "SAYANTAN PAL",
        "year": 2025,
        "handle": "Sayantan627",
        "gender": "male",
    },
    {
        "name": "Prinshu kumar",
        "year": 2025,
        "handle": "prinshuPK",
        "gender": "male",
    },
    {
        "name": "Anupriya",
        "year": 2025,
        "handle": "Anupriya_2.8",
        "gender": "female",
    },
    {
        "name": "Ankit Kumar",
        "year": 2025,
        "handle": "codewithankit",
        "gender": "male",
    },
    {
        "name": "Ankit Mishra",
        "year": 2025,
        "handle": "ankitm03012004",
        "gender": "male",
    },
    {
        "name": "Sayantan Datta",
        "year": 2025,
        "handle": "Sayantan07",
        "gender": "male",
    },
    {
        "name": "Vaibhav Singh",
        "year": 2025,
        "handle": "star_saber",
        "gender": "male",
    },
    {
        "name": "Anurag Banerjee",
        "year": 2025,
        "handle": "anurag_8b",
        "gender": "male",
    },
    {
        "name": "Raushan Singh",
        "year": 2024,
        "handle": "raushnn",
        "gender": "male",
    }
]

DATA = {r["handle"]: r for r in RAW_DATA}
HANDLES_LIST = ';'.join([r["handle"] for r in RAW_DATA])
#  anishde85,manish.17,coder_sounak
